### ISSUE TITLE
Option to hide sidebar in visual builder for better previewing

### ISSUE THREAD

**Issue by benjamintennant** [downshiftorg/prophoto7-issues#352] opened 2018-06-22 19:11 UTC
It can be difficult to see what the site will really look like in the Visual Builder when on a smaller screen. An option for hiding the sidebar would help give a more accurate presentation, especially for laptop and desktop modes.

**Comment by benjamintennant** [comment] 2018-06-22 19:11
+1 Yvonne Blume ticket 182304

**Comment by j-arens** [comment] 2019-06-05 16:00
Duplicate of https://github.com/downshiftorg/prophoto7-issues/issues/116

**Closed** 2023-07-18 17:18 UTC
Labels: enhancement, top-picks-1, matt-queue-1
