### ISSUE TITLE
Hide page title on specific pages/posts

### ISSUE THREAD

**Issue by meatwad5675** [downshiftorg/prophoto7-issues#432] opened 2018-08-15 19:16 UTC

**Comment by lalunecreative** [comment] 2018-08-15 22:26
Could we keep this out of the actual wordpress page area and just add it to the builder? It's easier to just turn the page title off in the wordpress content module.

**Comment by j-arens** [comment] 2018-08-17 15:44
https://github.com/downshiftorg/prophoto7-issues/issues/298

**Comment by postmastersteve** [comment] 2018-08-20 21:28
duplicate of #298

**Closed by postmastersteve** 2018-08-20 21:28 UTC
