### ISSUE TITLE
Fetch gallery posts on visual builder mount

### ISSUE THREAD

**Issue by j-arens** [downshiftorg/prophoto7-issues#390] opened 2018-07-20 18:35 UTC
Currently we only fetch all the users gallery posts on `componentDidMount` of the galleries library. This is a problem when a user is trying to select a gallery in some other customization (like block background galleries) before they've visited the galleries library in the sidebar and loaded in all the gallery posts. The one caveat is that we need to be careful that fetching of gallery posts on visual builder mounted is done in the background (service worker?) to prevent UI jank in cases where users have a lot of galleries.

**Comment by benjamintennant** [comment] 2018-12-11 14:41
+1 Sarah Harrigan ticket 188335

**Comment by benjamintennant** [comment] 2019-02-07 22:00
+1 Lance Lanagan ticket 190630

**Comment by postmastersteve** [comment] 2019-04-17 19:09
duplicate of #600

**Closed by postmastersteve** 2019-04-17 19:09 UTC
Labels: bug, galleries, top-picks-bt, top-picks-s, usability
