### ISSUE TITLE
Alphabatize or add filter options Visual Builder page/gallery selection

### ISSUE THREAD

**Issue by benjamintennant** [downshiftorg/prophoto7-issues#616] opened 2018-12-18 22:27 UTC
When selecting a page or a gallery from a menu item, the pages are not alphabetized so it can be hard to find the correct one. This is true in other areas as well, like when connecting layouts to galleries or pages, or when selecting a gallery to add into page content areas.

![capture 2](https://user-images.githubusercontent.com/12831291/50186791-eb4f7780-02e9-11e9-9620-365a6d4e9373.jpg)

**Comment by benjamintennant** [comment] 2019-01-07 20:31
+1 Davide Zanoni ticket 188172

**Comment by benjamintennant** [comment] 2019-01-22 15:22
+1 Gina Logan ticket 189755 - has lots of galleries and finds it difficult to select in a "Gallery" menu item.

**Comment by benjamintennant** [comment] 2019-02-21 13:30
+1 Benjamin Brammeier from FB

**Comment by benjamintennant** [comment] 2019-02-21 13:30
+1 Sandy Armenteros from FB

**Comment by benjamintennant** [comment] 2019-02-25 21:59
+1 Blanca Whalen ticket 191550

**Comment by postmastersteve** [comment] 2019-04-17 19:00
duplicate of #678

**Closed by postmastersteve** 2019-04-17 19:00 UTC
Labels: top-picks-s, usability, visual-builder
