### ISSUE TITLE
Add support for WordPress dropcap controls

### ISSUE THREAD

**Issue by postmastersteve** [downshiftorg/prophoto7-issues#711] opened 2019-03-29 21:29 UTC
Wordpress 5 provides a new dropcap toggle for all paragraph blocks. By default, the WP front-end CSS gives this a very specific height of `8.4em` which assumes a specific paragraph line-height value. ProPhoto provides adjustable line-height which can cause wrapped lines to butt up against the character.

Consider giving ProPhoto control over dropcap sizing, or consider scaling the dropcap letter to coordinate with the paragraph line height intelligently. Or, add margin below the dropcap letter.

**Comment by postmastersteve** [comment] 2019-03-29 21:29
+1 Samantha Culp and Rachel Thatcher ticket 192891

**Comment by j-arens** [comment] 2019-06-05 16:40
Duplicate of https://github.com/downshiftorg/prophoto7-issues/issues/427

**Closed by j-arens** 2019-06-05 16:40 UTC
Labels: feature, fonts
