### ISSUE TITLE
Re-evaluate where we put hamburger/slideout settings

### ISSUE THREAD

**Issue by meatwad5675** [downshiftorg/prophoto7-issues#541] opened 2018-10-08 19:24 UTC
The way that the hamburger/slideout settings are split up between the slideout block and the layout is weird and should be re-thought.

https://prophotoblogs.zendesk.com/agent/tickets/186389

**Comment by postmastersteve** [comment] 2018-10-08 19:25
Zendesk ticket #[186389](https://prophotoblogs.zendesk.com/agent/tickets/186389) has been linked to this issue.

**Comment by postmastersteve** [comment] 2019-03-12 16:00
closing - duplicate of #339

**Closed by postmastersteve** 2019-03-12 16:00 UTC
Labels: Zendesk, bt top-picks, enhancement
