### ISSUE TITLE
Allow for deletion of form log entries

### ISSUE THREAD

**Issue by benjamintennant** [downshiftorg/prophoto7-issues#371] opened 2018-07-09 21:11 UTC
Form log entries in "ProPhoto > Form Log" do not have a delete button. Add a delete button for better form log management.

**Comment by benjamintennant** [comment] 2018-07-09 21:12
+1 Marek Lukacko ticket 180942

**Comment by postmastersteve** [comment] 2018-08-14 20:30
duplicate of #274

**Closed by postmastersteve** 2018-08-14 20:30 UTC
Labels: forms
