### ISSUE TITLE
Grid item centering (import parity concern...)

### ISSUE THREAD

**Issue by meatwad5675** [downshiftorg/prophoto7-issues#208] opened 2018-05-31 03:42 UTC
<a href="https://github.com/jaredh159"><img src="https://avatars3.githubusercontent.com/u/7050938?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [jaredh159](https://github.com/jaredh159)**
_Wednesday Apr 25, 2018 at 19:12 GMT_
_Originally opened as https://github.com/downshiftorg/prophoto/issues/3192_

----

In P6, in situations where a grid did not fill the full width of it's parent element, the items centered, like as shown here (from _Montgomery_ design):

![2018-04-25_15-06-25](https://user-images.githubusercontent.com/7050938/39267468-e0da0626-489a-11e8-9e55-cd3c6207d4f9.png)

In P7, the items are left-aligning, causing what appears to be an import bug:

![2018-04-25_15-06-46](https://user-images.githubusercontent.com/7050938/39267478-ece82baa-489a-11e8-8e3d-d95a64dba4ca.png)

**Comment by postmastersteve** [comment] 2018-07-10 13:42
Closing - duplicate of #208

**Closed by postmastersteve** 2018-07-10 13:42 UTC
Labels: bug, grids
