### ISSUE TITLE
Global Wordpress favicon should be in ProPhoto settings

### ISSUE THREAD

**Issue by meatwad5675** [downshiftorg/prophoto7-issues#483] opened 2018-08-31 15:26 UTC
The favicon option in WordPress under Customizer > Site Identity is global across themes and should be exposed in ProPhoto settings somewhere

**Comment by benjamintennant** [comment] 2018-09-27 15:37
connected to #260

**Comment by postmastersteve** [comment] 2018-10-01 14:52
closing - duplicate of #260

**Closed by postmastersteve** 2018-10-01 14:52 UTC
Labels: enhancement
