### ISSUE TITLE
Comment vertical padding changes not applying properly in Visual Builder

### ISSUE THREAD

**Issue by benjamintennant** [downshiftorg/prophoto7-issues#498] opened 2018-09-14 13:18 UTC
If you make changes to the vertical padding slider in "WordPress Content Module > Comment Styles > Comment Form Fields > Vertical Padding" the changes don't visualize properly in the visual builder.... unless you have the cursor in the comment field. 

Video of the problem
https://www.screencast.com/t/dmxq5rWAG

Video showing it working with cursor in comment field. 
http://screenshots.pro.photo/2018-09-13_17-10-05.mp4

**Comment by postmastersteve** [comment] 2018-09-25 21:52
duplicate of #171

**Closed by postmastersteve** 2018-09-25 21:52 UTC
Labels: bug
