### ISSUE TITLE
Add checkbox field type for multiple selections

### ISSUE THREAD

**Issue by benjamintennant** [downshiftorg/prophoto7-issues#368] opened 2018-07-05 14:57 UTC
Users would like to be able to create a group of options which visitors can select from, allowing for one or more choices to be submitted. See older issue with comments at https://github.com/downshiftorg/prophoto-issues/issues/783

**Comment by benjamintennant** [comment] 2018-07-30 20:12
+1 Jen Thalmann Maguire from Facebook support group

**Comment by postmastersteve** [comment] 2018-10-01 13:12
closing - duplicate of #450

**Closed by postmastersteve** 2018-10-01 13:12 UTC
Labels: forms
