### ISSUE TITLE
Add controls for ordered and unordered lists in text module

### ISSUE THREAD

**Issue by postmastersteve** [downshiftorg/prophoto7-issues#15] opened 2018-05-29 21:24 UTC
Text modules need buttons for creating ordered `<ol>` and unordered `<ul>` lists within the content.

**Comment by benjamintennant** [comment] 2018-11-15 20:32
+1 Maria Wideman from Facebook group

**Comment by benjamintennant** [comment] 2018-11-15 20:32
+1 Ann-Louise from Facebook group

**Comment by benjamintennant** [comment] 2019-03-06 12:47
Duplicate of #348

**Closed** 2019-03-29 18:46 UTC
Labels: enhancement, modules
