### ISSUE TITLE
Improve rotation support for tile layers

### ISSUE THREAD

**Issue by postmastersteve** [downshiftorg/prophoto7-issues#377] opened 2018-07-17 14:06 UTC
ProPhoto 6 permitted tile layers to be rotated in positive or negative directions.
Some designs create a "spinning" effect on hover which can only be achieved with rotations **beyond** 360º in either direction.

E.g. with P6 you could rotate a layer -45º for the lines in a mobile menu button to create an X when active. ProPhoto 7 is able to _import_ negative values from P6 but doesn't allow users to set below 0º or above 360º with the rotate controls.

- Please add the ability for rotate controls to go negative.
- Please add the ability for rotation values to be typed so users can exceed 360º.

**Comment by postmastersteve** [comment] 2018-07-17 14:06
+1 Jonathan Adams ticket 183324

**Comment by danjonlam** [comment] 2022-02-09 15:58
Duplicate of:
https://github.com/downshiftorg/prophoto7-issues/issues/756

**Closed by danjonlam** 2022-02-09 15:58 UTC
Labels: enhancement, tiles, usability
