### ISSUE TITLE
WP content module controls are hidden in some scenarios (date in header, etc.)

### ISSUE THREAD

**Issue by postmastersteve** [downshiftorg/prophoto7-issues#604] opened 2018-12-10 18:07 UTC
This Github issue is synchronized with Zendesk:

**Ticket ID:** [#187601](https://prophotoblogs.zendesk.com/agent/tickets/187601)
**Priority:** high
**Group:** Developers
**Requester:** benjamin@pro.photo
**Organization:** Downshift
**Assignee:** Matt Dietsche
**Issue escalated by:** Matt Dietsche

**Original ticket description:**

<blockquote><div class="zd-comment">When grid excerpts are enabled (or were enabled when excerpts were turned on), the "Header Styles" tab disappears. This prevents people from accessing the archive type page heading options on archive pages with grid excerpts. Here is a video showing you what's going on. <br><br><a href="http://screenshots.pro.photo/2018-11-15_10-50-12.mp4" rel="noreferrer">http://screenshots.pro.photo/2018-11-15_10-50-12.mp4</a> <br>

<span class="collapse-signature"></span><div class="signature">
<p dir="auto">Benjamin Tennant<br>
ProPhoto Support</p>
<p dir="auto">Follow us for the latest ProPhoto news and updates:<br>
<a href="https://www.twitter.com/prophotoblogs/" rel="noreferrer">https://www.twitter.com/prophotoblogs/</a></p>
</div>
</div></blockquote>

**Comment by postmastersteve** [comment] 2019-01-07 15:47
duplicate of #563

**Comment by benjamintennant** [comment] 2019-03-06 12:56
duplicate of #295

**Comment by postmastersteve** [comment] 2019-03-26 19:14
+1 Justina Bilodeau ticket 188809

**Comment by postmastersteve** [comment] 2019-03-26 19:14
+1 Claude Masselot ticket 189024

**Comment by postmastersteve** [comment] 2019-03-26 19:14
+1 Amy Kimball ticket 189244

**Comment by postmastersteve** [comment] 2019-03-26 19:14
+1 cedric ticket 189095

**Comment by postmastersteve** [comment] 2019-03-26 19:15
+1 Anna ticket 192591

**Comment by benjamintennant** [comment] 2019-04-11 15:57
+1 amie ticket 193207 - wants to style archive page header

**Comment by benjamintennant** [comment] 2019-04-23 18:41
+1 Simone Anne ticket 193631

**Comment by benjamintennant** [comment] 2019-04-24 20:33
+1 Brian Rickey ticket 193696

**Comment by postmastersteve** [comment] 2019-05-01 18:05
+1 Pasha Belman ticket 193889

**Closed** 2022-02-09 15:26 UTC
Labels: bug, Zendesk, top-picks, top-picks-bt, top-picks-s
