### ISSUE TITLE
url inputs should make user aware of relative or absolute

### ISSUE THREAD

**Issue by meatwad5675** [downshiftorg/prophoto7-issues#90] opened 2018-05-31 03:13 UTC
<a href="https://github.com/Ramshackle-Jamathon"><img src="https://avatars3.githubusercontent.com/u/5943242?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [Ramshackle-Jamathon](https://github.com/Ramshackle-Jamathon)**
_Friday Feb 09, 2018 at 18:41 GMT_
_Originally opened as https://github.com/downshiftorg/prophoto/issues/2550_

----

inputs for urls should inform the user if they will be relative or absolute urls

google.com vs www.google.com vs http://www.google.com

**Comment by postmastersteve** [comment] 2019-03-12 21:16
closing, duplicate of #692

**Closed** 2019-03-12 21:16 UTC
Labels: duplicate, enhancement
